add support for additional arbitrary tweaks to the verifying key, par…
arminsabouri/frost pull request #1
Opened 2024-02-14 19:28 UTC by 0xBEEFCAF3

…tial signatures and signature aggregation

2024-02-14 19:36 UTC, stevenroose requested changes
sorry, ended up repeating that comment a ton of times :/

2024-02-14 19:36 UTC, stevenroose commented on frost-core/src/lib.rs
> +    #[cfg_attr(feature = "serde", serde(skip))]
Shouldn't skip the serialization of this

2024-02-14 19:36 UTC, stevenroose commented on frost-core/src/round2.rs
> +        additional_tweak: &Option<Vec<u8>>,
`Option<&[u8]>` is kinda identical but more idiomatic

2024-02-14 19:36 UTC, stevenroose commented on frost-core/src/signing_key.rs
> +        additional_tweak: &Option<Vec<u8>>,
`Option<&[u8]>` (btw you can get it at call-site by using `.as_ref()`

2024-02-14 19:36 UTC, stevenroose commented on frost-core/src/traits.rs
> +        arbitrary_tweak: &Option<Vec<u8>>,
`Option<&[u8]>`

2024-02-14 19:36 UTC, stevenroose commented on frost-core/src/traits.rs
> +        arbitrary_tweak: &Option<Vec<u8>>,
`Option<&[u8]>`

2024-02-14 19:36 UTC, stevenroose commented on frost-core/src/traits.rs
> +        arbitrary_tweak: &Option<Vec<u8>>,
`Option<&[u8]>`

2024-02-14 19:36 UTC, stevenroose commented on frost-core/src/traits.rs
> +        arbitrary_tweak: &Option<Vec<u8>>,
`Option<&[u8]>`

2024-02-14 19:36 UTC, stevenroose commented on frost-core/src/traits.rs
> +        additional_tweak: &Option<Vec<u8>>,
`Option<&[u8]>`

2024-02-14 19:36 UTC, stevenroose commented on frost-core/src/traits.rs
> +        additional_tweak: &Option<Vec<u8>>,
`Option<&[u8]>`

2024-02-14 19:36 UTC, stevenroose commented on frost-core/src/verifying_key.rs
> +        additional_tweak: &Option<Vec<u8>>,
`Option<&[u8]>`

2024-02-14 19:36 UTC, stevenroose commented on frost-core/src/verifying_key.rs
> +        additional_tweak: &Option<Vec<u8>>,
`Option<&[u8]>`

2024-02-14 19:36 UTC, stevenroose commented on frost-secp256k1-tr/src/lib.rs
> +    data: &Vec<u8>,
`&[u8]`

2024-02-14 19:36 UTC, stevenroose commented on frost-secp256k1-tr/src/lib.rs
> +    additional_tweak: &Option<Vec<u8>>,
`Option<&[u8]>`

2024-02-14 19:36 UTC, stevenroose commented on frost-secp256k1-tr/src/lib.rs
> +    additional_tweak: &Option<Vec<u8>>,
`Option<&[u8]>`

2024-02-14 19:36 UTC, stevenroose commented on frost-secp256k1-tr/src/lib.rs
> +    additional_tweak: &Option<Vec<u8>>,
`Option<&[u8]>`

2024-02-14 19:36 UTC, stevenroose commented on frost-secp256k1-tr/src/lib.rs
> +        additional_tweak: &Option<Vec<u8>>,
`Option<&[u8]>`

2024-02-14 19:36 UTC, stevenroose commented on frost-secp256k1-tr/src/lib.rs
> +        additional_tweak: &Option<Vec<u8>>,
`Option<&[u8]>`

2024-02-14 19:36 UTC, stevenroose commented on frost-secp256k1-tr/src/lib.rs
> +        additional_tweak: &Option<Vec<u8>>,
`Option<&[u8]>`

2024-02-14 19:36 UTC, stevenroose commented on frost-secp256k1-tr/src/lib.rs
> +        additional_tweak: &Option<Vec<u8>>,
`Option<&[u8]>`

2024-02-14 19:36 UTC, stevenroose commented on frost-secp256k1-tr/src/lib.rs
> +        additional_tweak: &Option<Vec<u8>>,
`Option<&[u8]>`

2024-02-14 19:36 UTC, stevenroose commented on frost-secp256k1-tr/src/lib.rs
> +        arbitrary_tweak: &Option<Vec<u8>>,
`Option<&[u8]>`

2024-02-14 19:41 UTC, arminsabouri commented
> sorry, ended up repeating that comment a ton of times :/

@stevenroose all good. I actually wanted specific feedback on that.

2024-12-13 14:56 UTC, 0xBEEFCAF3 commented
Closing replaced by #2

2024-12-13 14:56 UTC, closed without merging